### ISSUE TITLE
血书作者添加 layout 和 wight 组件

### ISSUE THREAD

**Issue by AnkoGo123** [flash2x/AnnieJS#17]
如果不知道layout和wight是什么，请百度cocos creator然后看下官方文档中的layout和wight 组件。万分感谢！

**Comment by AnkoGo123** [comment]
同时，每一个渲染节点都应该能添加子节点才对，而不是只有container和stage才能添加节点，这是不合理的，具体请参考cocos creator，这样方能领会为什么要这样做。。

**Comment by anlun214** [comment]
好的，你的建议会听取，在日后的版本中如果有机会一定融入进来。
